- hosts: node
  become: yes
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/azureuser/Deployment.yml
    - name: create new service
      command: kubectl apply -f /home/azureuser/Service.yml